import type { StudioSnapshot, EditProject, ClipAsset } from '../shared/contracts';
export const uid = () => crypto.randomUUID();
export const now = () => new Date().toISOString();
export const makeProject = (clip: ClipAsset): EditProject => ({ id: uid(), name: clip.name, assetId: clip.id, updatedAt: now(), tracks: [{ id: uid(), kind: 'video', name: 'Gameplay', segments: [{ id: uid(), assetId: clip.id, inMs: 0, outMs: clip.durationMs, offsetMs: 0, gain: 1, fadeInMs: 0, fadeOutMs: 0 }] }], aspect: '16:9', cropX: 50, cropY: 50, webcam: false, safeAreas: true, captions: [], captionStyle: { font: 'Arial', size: 32, color: '#ffffff', position: 'bottom' }, preset: 'Clean Highlight', musicHandle: null, musicGain: 0.3, originalGain: 1 });
export function makeFixtures(): StudioSnapshot {
    const clips: ClipAsset[] = [['The final round', 'Rainbow Six Siege', 28000, ['Clutch', 'Ranked']], ['Perfect timing', 'Destiny 2', 42000, ['PvP', 'Favorite']], ['One more round', 'Rainbow Six Siege', 61000, ['Squad']]].map(([name, game, durationMs, tags], i) => ({ id: `clip-${i}`, name: name as string, game: game as string, durationMs: durationMs as number, tags: tags as string[], sessionId: 'session-history', createdAt: '2026-10-04T21:32:00Z', favorite: i === 1, status: 'ready', mediaHandle: null, thumbnailUrl: null, fixture: true }));
    const available = { available: true, reason: null };
    const unavailable = (reason: string) => ({ available: false, reason });
    return { apiVersion: 1, mode: 'demo', capabilities: { obs: available, recording: available, replay: available, preview: unavailable('Import a local video to preview real media. OBS preview requires the desktop service.'), launch: available, obsAudio: available, windowsAudio: unavailable('Windows audio control requires a supported desktop device adapter.'), import: available, export: available, transcription: unavailable('Optional local transcription is not installed.'), telemetry: unavailable('Browser demo cannot read game FPS, encoder statistics or disk space.'), streaming: available }, obs: { connection: 'disconnected', scene: 'Gameplay', scenes: ['Gameplay', 'Starting Soon', 'Just Chatting', 'Be Right Back'], sources: ['Game Capture', 'Microphone', 'Webcam'], recording: false, replayBuffer: false, streaming: false, streamDestination: null, outputFps: null, encoderSkippedFrames: null, previewUrl: null }, audio: [{ id: 'microphone', name: 'Microphone', scope: 'obs', deviceName: 'Demo · USB microphone', gain: 0.8, muted: false, level: null }, { id: 'game', name: 'Game audio', scope: 'obs', deviceName: 'Demo · Desktop Audio', gain: 0.7, muted: false, level: null }, { id: 'music', name: 'Music', scope: 'obs', deviceName: 'Demo · Media source', gain: 0.3, muted: false, level: null }], profiles: [{ id: 'siege', name: 'Siege Night', game: 'Rainbow Six Siege', gamePath: 'C:\\Games\\RainbowSix.exe', scene: 'Gameplay', destination: 'C:\\Users\\drift\\Videos\\Drift', replayDurationMs: 30000, audioPreset: 'Balanced', companionApps: [], hotkey: 'Ctrl+Shift+F8' }, { id: 'destiny', name: 'Orbit Sessions', game: 'Destiny 2', gamePath: 'steam://rungameid/1085660', scene: 'Gameplay', destination: 'C:\\Users\\drift\\Videos\\Drift', replayDurationMs: 45000, audioPreset: 'Balanced', companionApps: [], hotkey: 'Ctrl+Shift+F9' }], selectedProfileId: 'siege', sessions: [{ id: 'session-history', profileId: 'siege', name: 'Last night · ranked', startedAt: '2026-10-04T20:00:00Z', endedAt: '2026-10-04T22:00:00Z', notes: 'A few good rounds with the squad.', events: [{ id: 'history-event', at: '2026-10-04T21:32:00Z', message: 'Illustrative highlight saved' }], clipIds: clips.map(c => c.id) }], activeSessionId: null, clips, projects: [], jobs: [], settings: { mediaFolder: 'C:\\Users\\drift\\Videos\\Drift', obsHost: '127.0.0.1', obsPort: 4455, appearance: 'studio', transcription: false, workerLimit: 1, shortcuts: true }, telemetry: { gameFps: null, diskFreeBytes: null }, warnings: [] };
}
