import {MediaArt} from '../components/MediaArt';
import {currentProfile} from '../profile';
import { useState } from 'react';
import { useSnapshot, useStudio } from '../context';
import { Button, Badge, Panel, Empty, time } from '../components/Primitives';
import { Icon } from '../components/Icon';
import { Arena, Ribbon } from '../components/Artwork';
export function CaptureControls() { const s = useSnapshot(); const { run, pending } = useStudio(); const connected = s.obs.connection === 'connected'; return <div className="capture-controls"><Button icon={s.obs.recording ? 'stop' : 'record'} onClick={() => void run('recording', { enabled: !s.obs.recording })} disabled={!connected || !s.capabilities.recording.available || pending.has('recording')} title={s.capabilities.recording.reason ?? undefined} variant={s.obs.recording ? 'danger' : ''}>{s.obs.recording ? 'Stop Recording' : 'Start Recording'}</Button><Button icon="replay" onClick={() => void run('replay', { enabled: !s.obs.replayBuffer })} disabled={!connected || !s.capabilities.replay.available || pending.has('replay')} title={s.capabilities.replay.reason ?? undefined}>{s.obs.replayBuffer ? 'Stop Buffer' : 'Start Buffer'}</Button><Button icon="clip" variant="primary" onClick={() => void run('saveReplay', undefined)} disabled={!connected || !s.capabilities.replay.available || !s.obs.replayBuffer || pending.has('saveReplay')} title={s.capabilities.replay.reason ?? undefined}>{pending.has('saveReplay') ? 'Saving…' : 'Save Replay'}</Button></div>; }
export function CommandCenter() {
    const s = useSnapshot();
    const { run, pending, navigate, openClip } = useStudio();
    const profile = currentProfile(s);
    const session = s.sessions.find(x => x.id === s.activeSessionId);
    const [steps, setSteps] = useState<{
        label: string;
        ok: boolean;
        detail: string;
    }[] | null>(null);
    const [canceled, setCanceled] = useState(false);
    const [preparing, setPreparing] = useState(false);
    const prepare = async () => { setCanceled(false); setPreparing(true); const r = await run('prepareSession', { profileId: profile.id }); setSteps(r?.steps ?? null); setPreparing(false); };
    const microphone=s.audio.find(a=>a.id==='microphone');
    const obsReady = s.obs.connection === 'connected';
    return <><div className="page-intro"><div><span className="eyebrow">YOUR PLAYBOOK, IN ONE PLACE</span><h1>Command Center<span className="heading-dot">.</span></h1><p>Less setup. More great moments.</p></div><Button icon="profiles" onClick={() => navigate('Profiles')}>Manage profiles</Button></div>
 <div className="command-top"><section className="session-hero"><div className="hero-grid"/><Ribbon /><div className="hero-content"><Badge tone="cyan">{session ? 'SESSION IN PROGRESS' : 'PLAY / CAPTURE / CREATE'}</Badge><h2>{session ? 'Make this session count.' : 'Ready for your next session.'}</h2><p>Your game, your scene, your sound.<br />One thoughtful starting point.</p><div className="profile-summary"><span className="game-mark">VI</span><div><strong>{profile.name}</strong><span>{profile.game} · {profile.replayDurationMs / 1000}s replay</span></div></div><div className="hero-actions"><Button icon={session ? 'stop' : 'play'} variant="primary" disabled={pending.has('startSession') || (!session && !obsReady)} onClick={() => void run(session ? 'endSession' : 'startSession', session ? undefined : { profileId: profile.id })}>{pending.has('startSession') ? 'Preparing…' : session ? 'End Session' : 'Start Session'}</Button><Button icon="check" variant="ghost" onClick={() => void prepare()} disabled={preparing}>Check setup</Button></div><small>{!obsReady ? 'Connect OBS in the panel to begin.' : 'Starting a session prepares the scene and replay buffer. Go Live is separate.'}</small></div></section>
 <Panel title="Session readiness" sub="A clear check before you play." className="readiness" actions={<Badge tone={obsReady ? 'cyan' : 'amber'}>{obsReady ? 'Demo connected' : 'Offline'}</Badge>}><div className="checklist">{[{ name: 'OBS connection', detail: obsReady ? 'Demo OBS service connected' : 'Waiting for connection', ok: obsReady }, { name: 'Game Capture', detail: obsReady ? 'Simulated source available' : 'Source check requires OBS', ok: obsReady }, { name: 'Replay buffer', detail: s.obs.replayBuffer ? 'Armed · simulated' : 'Ready to start with your session', ok: s.obs.replayBuffer }, { name: 'Microphone', detail: 'Demo USB microphone · signal unavailable', ok: false }, { name: 'Media destination', detail: profile.destination, ok: !s.warnings.includes('Insufficient storage') }].map(x => <div key={x.name} className="check-row"><span className={`check-symbol ${x.ok ? 'ok' : ''}`}><Icon name={x.ok ? 'check' : 'alert'} size={14}/></span><div><strong>{x.name}</strong><small>{x.detail}</small></div></div>)}</div><Button icon="link" variant="full" disabled={pending.has('connect')} onClick={() => void run(obsReady ? 'disconnect' : 'connect', obsReady ? undefined : { host: s.settings.obsHost, port: s.settings.obsPort })}>{pending.has('connect') ? 'Connecting…' : obsReady ? 'Disconnect demo OBS' : 'Connect demo OBS'}</Button><p className="fine-print">{s.mode === 'demo' ? 'No real OBS or game process is controlled.' : 'Actions use the desktop service.'}</p></Panel></div>
 {preparing && <Panel><div className="row"><p>Checking profile steps…</p><Button onClick={() => { setCanceled(true); setPreparing(false); }}>Cancel preparation</Button></div></Panel>}{steps && !canceled && <Panel title="Preflight results" actions={<Button onClick={() => setSteps(null)} variant="ghost">Dismiss</Button>}><div className="preflight-results">{steps.map(x => <div key={x.label}><Badge tone={x.ok ? 'cyan' : 'amber'}>{x.ok ? 'Passed' : 'Needs attention'}</Badge><strong>{x.label}</strong><small>{x.detail}</small></div>)}</div></Panel>}
 <div className="command-mid"><Panel title="Capture desk" sub="Hold on to the moments worth keeping." actions={<Button variant="ghost" icon="arrow" onClick={() => navigate('Stream Controls')}>Open controls</Button>}><div className="capture-preview">{s.obs.previewUrl?<img className="obs-preview" src={s.obs.previewUrl} alt="OBS program preview"/>:<Arena/>}<div className="preview-overlay"><Badge>{s.obs.scene}</Badge><span>{s.obs.previewUrl?'OBS program preview':'No live OBS preview · illustrative scene'}</span></div></div><CaptureControls /><div className="inline-device"><Icon name="mic"/><span>{microphone?.deviceName??'No microphone source configured'}</span><button onClick={() => void run('audio', { id: 'microphone', gain: microphone?.gain??0, muted: !microphone?.muted })} disabled={!obsReady || !microphone || !s.capabilities.obsAudio.available || pending.has('audio')}>{microphone?.muted ? 'Unmute' : 'Mute'}</button><span className="muted">Signal unavailable</span></div></Panel>
 <Panel title="Session pulse" sub={session ? session.name : 'Your next session starts here.'} className="pulse"><div className="pulse-metrics"><div><span>SESSION</span><strong>{session ? 'Active' : 'Standby'}</strong></div><div><span>CLIPS SAVED</span><strong>{session?.clipIds.length ?? 0}<small> this session</small></strong></div></div><div className="activity-feed">{session?.events.slice(-4).reverse().map(e => <div key={e.id}><span className="activity-dot"/><div><p>{e.message}</p><small>{new Date(e.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></div></div>) ?? <Empty icon="sessions" title="All set for a fresh start" detail="Session events appear here as you capture."/>}</div><div className="telemetry"><span>Game FPS <strong>{s.telemetry.gameFps??'Unavailable'}</strong></span><span>OBS output FPS <strong>{s.obs.outputFps??'Unavailable'}</strong></span><small>{s.capabilities.telemetry.reason ?? 'Waiting for measurements.'}</small></div></Panel></div>
 <Panel title="Recent highlights" sub="From the last round to the next edit." actions={<Button icon="arrow" variant="ghost" onClick={() => navigate('ClipForge')}>Open ClipForge</Button>}>{s.clips.length ? <div className="highlights">{s.clips.slice(0, 3).map((c, i) => <button className="highlight-card" key={c.id} onClick={() => openClip(c)}><div className="highlight-art"><MediaArt clip={c} variant={i}/><span className="duration">{time(c.durationMs)}</span><span className="play-float"><Icon name="play"/></span></div><div className="highlight-info"><div><strong>{c.name}</strong><span>{c.game}</span></div><Icon name="arrow"/></div><div className="highlight-tags"><Badge tone={i === 1 ? 'violet' : 'cyan'}>{c.tags[0] ?? 'Highlight'}</Badge><small>{c.fixture ? 'Demo fixture' : c.status === 'missing' ? 'Missing file' : 'Local import'}</small></div></button>)}</div> : <Empty title="Your highlights live here" detail="Start the replay buffer and save a highlight, or import a recording in ClipForge."/>}</Panel>
 </>;
}
